
import { Prediction } from "./types";

export const PREDICTIONS_DATA: Prediction[] = [
  // ==========================================
  // BATCH 1: ChatGPT (January 03, 2026)
  // ==========================================
  
  // BRAZIL (BZ-01 to BZ-13)
  {
    id: "bz-26-01",
    code: "BZ-01",
    model: "ChatGPT",
    scope: "Brazil",
    category: "Politics",
    content: "Administrative Reform Approval: The National Congress will pass a comprehensive administrative reform to streamline civil service costs.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Growing fiscal pressure and a shift in legislative priority toward long-term structural solvency."
  },
  {
    id: "bz-26-02",
    code: "BZ-02",
    model: "ChatGPT",
    scope: "Brazil",
    category: "Finance & Economy",
    content: "Inflation Target recalibration: The Central Bank of Brazil will successfully maintain inflation within the new 3% target corridor despite global volatility.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "High interest rates throughout 2025 will have successfully cooled domestic demand, creating a stable baseline for 2026."
  },
  {
    id: "bz-26-03",
    code: "BZ-03",
    model: "ChatGPT",
    scope: "Brazil",
    category: "Tech",
    content: "Embraer eVTOL Public Flight: The first full-scale public demonstration flight of Eve's eVTOL will occur over São Paulo.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Certification milestones in 2025 and strategic pressure to dominate the Latin American urban air mobility market."
  },
  {
    id: "bz-26-04",
    code: "BZ-04",
    model: "ChatGPT",
    scope: "Brazil",
    category: "Politics",
    content: "Amazon Deforestation Record: Deforestation rates in the Legal Amazon will hit a 10-year low due to intensified AI-driven monitoring.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "bz-26-05",
    code: "BZ-05",
    model: "ChatGPT",
    scope: "Brazil",
    category: "Finance & Economy",
    content: "Petrobras Renewables Pivot: The company will announce that 20% of its CAPEX is now officially redirected to green hydrogen and offshore wind.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "bz-26-06",
    code: "BZ-06",
    model: "ChatGPT",
    scope: "Brazil",
    category: "Crypto",
    content: "DREX Retail Rollout: The Digital Real (DREX) will enter its first large-scale retail pilot program with selected major banks.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "bz-26-07",
    code: "BZ-07",
    model: "ChatGPT",
    scope: "Brazil",
    category: "Sports",
    content: "Football Retirement Shock: A top-tier Brazilian veteran (likely Neymar) will announce a definitive timeline for retirement after the 2026 World Cup.",
    confidence: 60,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "bz-26-08",
    code: "BZ-08",
    model: "ChatGPT",
    scope: "Brazil",
    category: "War",
    content: "Federal AI Policing: A major federal initiative will be launched to use predictive AI models for urban security in Rio and Salvador.",
    confidence: 65,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "bz-26-09",
    code: "BZ-09",
    model: "ChatGPT",
    scope: "Brazil",
    category: "Tech",
    content: "6G Research Hub: Campinas will be designated as the Southern Hemisphere's primary 6G research and development hub.",
    confidence: 50,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "bz-26-10",
    code: "BZ-10",
    model: "ChatGPT",
    scope: "Brazil",
    category: "Politics",
    content: "Mercosur-EU Signature: After decades, the final ratification of the Mercosur-EU trade agreement will be signed by all parties.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "bz-26-11",
    code: "BZ-11",
    model: "ChatGPT",
    scope: "Brazil",
    category: "Politics",
    content: "Third Way Surge: A tech-centric 'Third Way' political movement will gain significant traction ahead of the 2026 elections.",
    confidence: 40,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "bz-26-12",
    code: "BZ-12",
    model: "ChatGPT",
    scope: "Brazil",
    category: "Finance & Economy",
    content: "Nubank Expansion: Nubank will reach 120 million global users, becoming the primary digital bank for the entire Latin American middle class.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "bz-26-13",
    code: "BZ-13",
    model: "ChatGPT",
    scope: "Brazil",
    category: "AI",
    content: "AI Literacy Program: The Ministry of Education will launch a nationwide program to integrate Generative AI tools in public high schools.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03"
  },

  // GLOBAL (GL-01 to GL-13)
  {
    id: "gl-26-01",
    code: "GL-01",
    model: "ChatGPT",
    scope: "Global",
    category: "AI",
    content: "Agentic Workflows: Reasoning-capable AI agents will autonomously handle 15% of global entry-level corporate analyst workflows.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gl-26-02",
    code: "GL-02",
    model: "ChatGPT",
    scope: "Global",
    category: "Finance & Economy",
    content: "India Economic Surge: India will officially surpass Germany to become the world's 4th largest economy.",
    confidence: 95,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gl-26-03",
    code: "GL-03",
    model: "ChatGPT",
    scope: "Global",
    category: "Tech",
    content: "Solid-State Battery Sales: The first commercial vehicle powered by a true solid-state battery will go on sale to the public.",
    confidence: 60,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gl-26-04",
    code: "GL-04",
    model: "ChatGPT",
    scope: "Global",
    category: "Politics",
    content: "Geoengineering Debate: Global temperatures will trigger the first formal UN-level debate on controlled Solar Radiation Management.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gl-26-05",
    code: "GL-05",
    model: "ChatGPT",
    scope: "Global",
    category: "AI",
    content: "mRNA Cancer Vaccines: Personalized mRNA-based cancer vaccines will enter pivotal Phase III trials with high efficacy reported.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gl-26-06",
    code: "GL-06",
    model: "ChatGPT",
    scope: "Global",
    category: "Tech",
    content: "Starship Lunar Orbit: SpaceX Starship will successfully complete its first commercial crewed loop around the Moon.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gl-26-07",
    code: "GL-07",
    model: "ChatGPT",
    scope: "Global",
    category: "Crypto",
    content: "Bitcoin Stability: Bitcoin will enter a 'Stability Phase,' maintaining a floor above $100k driven by sovereign wealth fund adoption.",
    confidence: 65,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gl-26-08",
    code: "GL-08",
    model: "ChatGPT",
    scope: "Global",
    category: "Politics",
    content: "4-Day Week Standard: At least three major EU countries will legislate the 4-day work week as the default labor standard.",
    confidence: 55,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gl-26-09",
    code: "GL-09",
    model: "ChatGPT",
    scope: "Global",
    category: "Tech",
    content: "AR Glasses Breakthrough: High-fidelity AR glasses will surpass smartwatches in quarter-over-quarter sales growth for the first time.",
    confidence: 60,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gl-26-10",
    code: "GL-10",
    model: "ChatGPT",
    scope: "Global",
    category: "Finance & Economy",
    content: "Regional Hub Surge: De-globalization will peak, with 40% of tech hardware manufacturing shifting to regional 'Friend-shoring' hubs.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gl-26-11",
    code: "GL-11",
    model: "ChatGPT",
    scope: "Global",
    category: "AI",
    content: "AGI-Lite Benchmark: A new industry-standard benchmark will declare the first model to achieve 'Human-Level General Reasoning' in specialized domains.",
    confidence: 40,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gl-26-12",
    code: "GL-12",
    model: "ChatGPT",
    scope: "Global",
    category: "Tech",
    content: "Fusion Net-Gain: Two private fusion startups will independently report sustained 'Net-Energy-Gain' for over 60 seconds.",
    confidence: 30,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gl-26-13",
    code: "GL-13",
    model: "ChatGPT",
    scope: "Global",
    category: "AI",
    content: "Lab-Grown Organs: The first successful transplant of a complex, 3D-bioprinted human organ will be completed without rejection.",
    confidence: 50,
    status: "Pending",
    timestamp: "2026-01-03"
  },

  // GEOPOLITICS (GP-01 to GP-12)
  {
    id: "gp-26-01",
    code: "GP-01",
    model: "ChatGPT",
    scope: "Geopolitics",
    category: "War",
    content: "Ukraine 'Frozen Conflict': The conflict in Eastern Europe will enter a 'Permanent Ceasefire' status, following a model similar to the Korean Peninsula.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Exhaustion of conventional munitions and a shift in Western political focus toward domestic stability."
  },
  {
    id: "gp-26-02",
    code: "GP-02",
    model: "ChatGPT",
    scope: "Geopolitics",
    category: "Politics",
    content: "China Demographic Policy: China will implement its most aggressive 'Pronatalist' policy in history, including direct state-funded child-rearing.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gp-26-03",
    code: "GP-03",
    model: "ChatGPT",
    scope: "Geopolitics",
    category: "Politics",
    content: "US Digital Constitutionalism: A landmark bipartisan bill in the US will establish the first 'Digital Bill of Rights' for AI-era data sovereignty.",
    confidence: 60,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gp-26-04",
    code: "GP-04",
    model: "ChatGPT",
    scope: "Geopolitics",
    category: "Politics",
    content: "Middle East Normalization: Saudi-Israel relations will be officially normalized through a historic regional trade and defense treaty.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gp-26-05",
    code: "GP-05",
    model: "ChatGPT",
    scope: "Geopolitics",
    category: "War",
    content: "EU Defense Cloud: The European Union will launch its own sovereign defense cloud and satellite constellation to reduce US reliance.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gp-26-06",
    code: "GP-06",
    model: "ChatGPT",
    scope: "Geopolitics",
    category: "War",
    content: "Arctic Naval Expansion: Russia and China will announce a joint permanent Arctic naval presence to secure the Northern Sea Route.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gp-26-07",
    code: "GP-07",
    model: "ChatGPT",
    scope: "Geopolitics",
    category: "Politics",
    content: "Cricket Diplomacy: India and Pakistan will resume full bilateral sports and limited cultural ties after years of total freeze.",
    confidence: 50,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gp-26-08",
    code: "GP-08",
    model: "ChatGPT",
    scope: "Geopolitics",
    category: "Politics",
    content: "AU Digital Passport: The African Union will finalize the technical architecture for a unified 'Digital AU Passport' for intra-continental travel.",
    confidence: 65,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gp-26-09",
    code: "GP-09",
    model: "ChatGPT",
    scope: "Geopolitics",
    category: "Finance & Economy",
    content: "Lithium OPEC: A formal mineral alliance between Chile, Argentina, Australia, and Bolivia will be established to control supply prices.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gp-26-10",
    code: "GP-10",
    model: "ChatGPT",
    scope: "Geopolitics",
    category: "Politics",
    content: "UNSC Reform Draft: A viable, consensus-based draft to expand the UN Security Council permanent seats will finally reach the floor.",
    confidence: 40,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gp-26-11",
    code: "GP-11",
    model: "ChatGPT",
    scope: "Geopolitics",
    category: "Tech",
    content: "RISC-V Tech Ban: The US will implement strict export controls on high-end RISC-V architectural blueprints to rival nations.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03"
  },
  {
    id: "gp-26-12",
    code: "GP-12",
    model: "ChatGPT",
    scope: "Geopolitics",
    category: "Politics",
    content: "ASEAN Cyber Sovereignty: SE Asian nations will begin construction of a shared regional data-firewall for 'Cyber-Sovereignty.'",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03"
  },

  // ==========================================
  // BATCH 2: XAI Grok 4.1 (January 03, 2026)
  // ==========================================

  // BRAZIL (BZ-14 to BZ-27)
  {
    id: "bz-grok-01",
    code: "BZ-14",
    model: "Grok",
    scope: "Brazil",
    category: "Politics",
    content: "Lula secures re-election in October 2026 with 52% in the second round against a unified right-wing opponent.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Incumbent advantage, social program expansions, and economic stabilization bolster support in Northeast Brazil."
  },
  {
    id: "bz-grok-02",
    code: "BZ-15",
    model: "Grok",
    scope: "Brazil",
    category: "Politics",
    content: "Supreme Court (STF) rules expand judicial oversight on Congress, leading to 3+ impeachment attempts against federal lawmakers.",
    confidence: 60,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Ongoing tensions from 2025 Lava Jato echoes fuel activist judiciary; precedents already invalidated 15% of congressional votes."
  },
  {
    id: "bz-grok-03",
    code: "BZ-16",
    model: "Grok",
    scope: "Brazil",
    category: "Finance & Economy",
    content: "GDP grows 2.8%, driven by agribusiness exports but hampered by potential U.S. tariffs.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Soybean and iron ore exports hit record highs, but global recession and BRICS-targeted tariffs cap manufacturing."
  },
  {
    id: "bz-grok-04",
    code: "BZ-17",
    model: "Grok",
    scope: "Brazil",
    category: "Finance & Economy",
    content: "Inflation stabilizes at 4.2%, with food prices rising 6% due to El Niño droughts.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Tight monetary policy succeeds, but climate impacts reduce harvest estimates, pressuring CPI."
  },
  {
    id: "bz-grok-05",
    code: "BZ-18",
    model: "Grok",
    scope: "Brazil",
    category: "Tech",
    content: "Brazil becomes Latin America's AI hub, with 500+ startups raising $2B in VC.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Government allocation of R$1B and Pix integration boost fintech valuations; major tech corridors attract global expansions."
  },
  {
    id: "bz-grok-06",
    code: "BZ-19",
    model: "Grok",
    scope: "Brazil",
    category: "Finance & Economy",
    content: "Petrobras dividends exceed R$100B, while the green energy pivot adds 20GW in renewables.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Pre-salt oil production peaks, funding transition; wind/solar auctions expected to be oversubscribed."
  },
  {
    id: "bz-grok-07",
    code: "BZ-20",
    model: "Grok",
    scope: "Brazil",
    category: "Crypto",
    content: "Crypto market cap in Brazil surpasses $50B, with 20M users via regulated ETFs.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "CVM ETF approvals and an 18% adoption rate grow amid dollar volatility; tax reforms stabilize trading."
  },
  {
    id: "bz-grok-08",
    code: "BZ-21",
    model: "Grok",
    scope: "Brazil",
    category: "Sports",
    content: "Brazil wins 2026 World Cup group stage but exits in the quarterfinals.",
    confidence: 50,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Squad led by Vinícius Jr. dominates qualifiers, but an aging defensive core falters against top-tier European teams."
  },
  {
    id: "bz-grok-09",
    code: "BZ-22",
    model: "Grok",
    scope: "Brazil",
    category: "Sports",
    content: "Flamengo wins Brasileirão, with average attendance hitting 50K per match.",
    confidence: 60,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Maracanã renovations and key contract extensions boost fan engagement and revenue."
  },
  {
    id: "bz-grok-10",
    code: "BZ-23",
    model: "Grok",
    scope: "Brazil",
    category: "Tech",
    content: "Cyberattacks on banks rise 40%, prompting a massive national CERT expansion.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "AI-enhanced phishing and scams trend up; government invests R$500M in specialized cybersecurity training."
  },
  {
    id: "bz-grok-11",
    code: "BZ-24",
    model: "Grok",
    scope: "Brazil",
    category: "Finance & Economy",
    content: "Unemployment drops to 7.2%, but significant inequality persists in urban favelas.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Service sector adds 1.5M jobs via tourism, but regional development gaps remain wide."
  },
  {
    id: "bz-grok-12",
    code: "BZ-25",
    model: "Grok",
    scope: "Brazil",
    category: "Politics",
    content: "Amazon deforestation falls 15% due to enhanced satellite enforcement.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Ibama's AI monitoring fines illegal logging; trade pressure forces zero-deforestation supply chains."
  },
  {
    id: "bz-grok-13",
    code: "BZ-26",
    model: "Grok",
    scope: "Brazil",
    category: "Crypto",
    content: "Mercado Bitcoin merges with a global exchange, valuation reaches $5B.",
    confidence: 60,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "High transaction volumes position it for a Nasdaq listing as regulatory clarity accelerates consolidation."
  },
  {
    id: "bz-grok-14",
    code: "BZ-27",
    model: "Grok",
    scope: "Brazil",
    category: "Tech",
    content: "5G covers 90% of urban areas, reducing the digital divide by 20%.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Aggressive spectrum auctions and telco investments enable massive IoT upgrades and infrastructure rollout."
  },

  // GLOBAL (GL-14 to GL-26)
  {
    id: "gl-grok-01",
    code: "GL-14",
    model: "Grok",
    scope: "Global",
    category: "Finance & Economy",
    content: "Global GDP grows 3.0%, led by Asian markets while Europe struggles.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "China infrastructure stimulus and India manufacturing surge offset U.S. tariffs on BRICS."
  },
  {
    id: "gl-grok-02",
    code: "GL-15",
    model: "Grok",
    scope: "Global",
    category: "Politics",
    content: "U.S. administration imposes 20% universal tariffs, sparking major WTO disputes.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Campaign promises materialize as executive orders; retaliation hits $500B in trade flows."
  },
  {
    id: "gl-grok-03",
    code: "GL-16",
    model: "Grok",
    scope: "Global",
    category: "Tech",
    content: "AI chip demand drives Nvidia revenue to $200B; open-source models dominate 60% of deployments.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Hyperscalers shift to open variants post-regulation; 2nm yields fuel AI in billions of edge devices."
  },
  {
    id: "gl-grok-04",
    code: "GL-17",
    model: "Grok",
    scope: "Global",
    category: "Crypto",
    content: "Bitcoin surpasses $150K, with total market cap hitting $4T amid massive ETF inflows.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Regulatory clarity and halving cycle effects; institutional adoption rises to 25% of portfolios."
  },
  {
    id: "gl-grok-05",
    code: "GL-18",
    model: "Grok",
    scope: "Global",
    category: "War",
    content: "Ukraine ceasefire holds through year-end, but Taiwan tensions escalate significantly.",
    confidence: 60,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Western aid fatigue pressures negotiations while naval incursions in the Pacific intensify."
  },
  {
    id: "gl-grok-06",
    code: "GL-19",
    model: "Grok",
    scope: "Global",
    category: "Politics",
    content: "Record heatwaves displace 50M people globally; renewables reach 40% of the energy mix.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "El Niño extension boosts solar/wind installs while extreme climate events force migration."
  },
  {
    id: "gl-grok-07",
    code: "GL-20",
    model: "Grok",
    scope: "Global",
    category: "Tech",
    content: "Apple launches high-fidelity AR glasses, capturing 20% of the wearables market.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Vision Pro success scales to lightweight consumer models; supply chain shifts mitigate regional risks."
  },
  {
    id: "gl-grok-08",
    code: "GL-21",
    model: "Grok",
    scope: "Global",
    category: "Sports",
    content: "USA hosts successful 2026 FIFA World Cup; Lionel Messi retires post-tournament.",
    confidence: 60,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Expanded 48-team format draws 5M attendees; legendary career caps at age 39."
  },
  {
    id: "gl-grok-09",
    code: "GL-22",
    model: "Grok",
    scope: "Global",
    category: "Tech",
    content: "Ransomware attacks double, prompting mandated quantum-resistant encryption in G7 nations.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "AI-enhanced exploits target critical infrastructure; NIST standards become Fortune 500 default."
  },
  {
    id: "gl-grok-10",
    code: "GL-23",
    model: "Grok",
    scope: "Global",
    category: "Politics",
    content: "Global fertility rate drops to 2.2, accelerating aging crises in Japan and Italy.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Urbanization and education trends persist; AI childcare pilots attempt to boost workforce participation."
  },
  {
    id: "gl-grok-11",
    code: "GL-24",
    model: "Grok",
    scope: "Global",
    category: "Finance & Economy",
    content: "ECB cuts rates to 1.5% to avert recession, despite inflating housing markets.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Economic stagnation in major EU powers forces dovish policy; energy independence stabilizes costs."
  },
  {
    id: "gl-grok-12",
    code: "GL-25",
    model: "Grok",
    scope: "Global",
    category: "Politics",
    content: "Saudi-Iran détente expands OPEC+, stabilizing global oil prices at $75-85/bbl.",
    confidence: 60,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Beijing-brokered joint ventures yield stability; Vision 2030 nears renewable targets."
  },
  {
    id: "gl-grok-13",
    code: "GL-26",
    model: "Grok",
    scope: "Global",
    category: "Tech",
    content: "mRNA cancer vaccines gain FDA approval for multiple cancers, treating 1M+ patients.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Phase 3 trials show 90% efficacy; biotech funding hits record highs post-pandemic."
  },

  // GEOPOLITICS (GP-13 to GP-24)
  {
    id: "gp-grok-01",
    code: "GP-13",
    model: "Grok",
    scope: "Geopolitics",
    category: "War",
    content: "U.S. deploys carrier strike groups to South China Sea as Taiwan arms sales exceed $10B.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "AUKUS pact continuity escalates maritime presence; blockade risks reach decade-high levels."
  },
  {
    id: "gp-grok-02",
    code: "GP-14",
    model: "Grok",
    scope: "Geopolitics",
    category: "War",
    content: "Russia-Ukraine frozen frontline holds via Minsk 3.0 talks, Russia retaining 20% territory.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "War fatigue and sanctions pressure Zelenskyy toward concessions by mid-year."
  },
  {
    id: "gp-grok-03",
    code: "GP-15",
    model: "Grok",
    scope: "Geopolitics",
    category: "War",
    content: "Israel strikes Iranian nuclear sites, prompting Hezbollah escalation but avoiding full-scale war.",
    confidence: 60,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "IAEA non-compliance reports fuel preemption; U.S. THAAD batteries successfully deter retaliation."
  },
  {
    id: "gp-grok-04",
    code: "GP-16",
    model: "Grok",
    scope: "Geopolitics",
    category: "War",
    content: "NATO full integration of Sweden and Finland complete; Eastern Flank bases double.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Rearmament leads to 2% GDP target breaches by most allies; Baltic security remains priority."
  },
  {
    id: "gp-grok-05",
    code: "GP-17",
    model: "Grok",
    scope: "Geopolitics",
    category: "Politics",
    content: "BRICS expansion reaches 10 members; de-dollarization trade reaches 30% in local currencies.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "mBridge CBDC pilots settle hundreds of billions, eroding traditional banking dominance."
  },
  {
    id: "gp-grok-06",
    code: "GP-18",
    model: "Grok",
    scope: "Geopolitics",
    category: "Politics",
    content: "Ladakh border pact stabilizes LAC, while Quad naval exercises intensify.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Regional infrastructure trades for de-escalation while U.S.-Japan arms to India counter BRI."
  },
  {
    id: "gp-grok-07",
    code: "GP-19",
    model: "Grok",
    scope: "Geopolitics",
    category: "War",
    content: "Africa Corps ousted from Sahel; ECOWAS forces stabilize regional juntas by year-end.",
    confidence: 60,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "AU standby brigade activates to fill security vacuum post-French/U.S. pullouts."
  },
  {
    id: "gp-grok-08",
    code: "GP-20",
    model: "Grok",
    scope: "Geopolitics",
    category: "War",
    content: "North Korea tests ICBMs, prompting a formal U.S.-ROK nuclear sharing agreement.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Artillery drills and ballistic tests shift public support in Seoul toward nuclear deterrence."
  },
  {
    id: "gp-grok-09",
    code: "GP-21",
    model: "Grok",
    scope: "Geopolitics",
    category: "War",
    content: "Arctic icebreaker standoffs rise by 50% as melting routes boost resource claims.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "F-35 patrols and contested EEZ overlaps create high-latitude friction over drilling rights."
  },
  {
    id: "gp-grok-10",
    code: "GP-22",
    model: "Grok",
    scope: "Geopolitics",
    category: "Politics",
    content: "Maduro regime collapses in Venezuela via internal coup following Essequibo failures.",
    confidence: 50,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Oil production strains PDVSA; U.S. sanctions and opposition unity trigger high-level elite defection."
  },
  {
    id: "gp-grok-11",
    code: "GP-23",
    model: "Grok",
    scope: "Geopolitics",
    category: "Politics",
    content: "France and Germany 'fiscal schism' delays EU budget; right-wing coalition rise in Germany.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Pension unrest and coalition fractures force a massive debt mutualization debate."
  },
  {
    id: "gp-grok-12",
    code: "GP-24",
    model: "Grok",
    scope: "Geopolitics",
    category: "Tech",
    content: "U.S-China cyber treaty signed; anti-satellite (ASAT) tests banned after regional incidents.",
    confidence: 60,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Large-scale hacks spur UN norms; Space Force budget shifts focus to contested orbit safety."
  },

  // ==========================================
  // BATCH 3: Gemini 3 Pro (January 03, 2026)
  // ==========================================

  // BRAZIL (BZ-28 to BZ-39)
  {
    id: "bz-gemini-01",
    code: "BZ-28",
    model: "Gemini",
    scope: "Brazil",
    category: "AI",
    content: "The 'Deepfake Election' Crisis triggers emergency TSE regulation as campaigns shift to synthetic reality.",
    confidence: 95,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "First campaign cycle dominated by hyper-realistic AI-generated disinformation, forcing 'digital watermark' protocols."
  },
  {
    id: "bz-gemini-02",
    code: "BZ-29",
    model: "Gemini",
    scope: "Brazil",
    category: "Crypto",
    content: "Drex (Digital Real) moves to full retail integration for smart contracts in asset transfers.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Operationalization reduces bureaucratic friction in real estate and vehicle transfers normalized for conservative investors."
  },
  {
    id: "bz-gemini-03",
    code: "BZ-30",
    model: "Gemini",
    scope: "Brazil",
    category: "Finance & Economy",
    content: "The 'Silver Economy' Pivot becomes the dominant retail strategy targeting the 60+ demographic.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Shift in purchasing power as demographic dividend ends; surge in aging-in-place technologies."
  },
  {
    id: "bz-gemini-04",
    code: "BZ-31",
    model: "Gemini",
    scope: "Brazil",
    category: "Finance & Economy",
    content: "Northeast Brazil officially becomes a global Green Hydrogen hub with major plant construction.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Driven by European demand for energy security and COP30 investment commitments in Ceará and Pentambuco."
  },
  {
    id: "bz-gemini-05",
    code: "BZ-32",
    model: "Gemini",
    scope: "Brazil",
    category: "Sports",
    content: "The 'Neymar-less' Era defines the World Cup narrative, focusing on cohesive tactical collectives.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Psychological decoupling from individual dependency; younger generation (Vinícius/Endrick) drives Semifinal run."
  },
  {
    id: "bz-gemini-06",
    code: "BZ-33",
    model: "Gemini",
    scope: "Brazil",
    category: "Tech",
    content: "The 'BYD Effect' forces a major Western automaker exodus or strategic merger in the region.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Chinese EV manufacturers capture 40%+ of mid-tier market, making legacy local manufacturing unsustainable."
  },
  {
    id: "bz-gemini-07",
    code: "BZ-34",
    model: "Gemini",
    scope: "Brazil",
    category: "Tech",
    content: "Biological Agro-Control adoption surpasses chemical inputs in growth percentage for the first time.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Rising costs of imported chemicals and proven efficacy of tropical agritech innovations."
  },
  {
    id: "bz-gemini-08",
    code: "BZ-35",
    model: "Gemini",
    scope: "Brazil",
    category: "War",
    content: "Biometric Data Ransomware specifically targets Fintechs as facial recognition becomes the banking standard.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Shift from password theft to biometric spoofing at scale, forcing Level 3 hardware-based liveness detection."
  },
  {
    id: "bz-gemini-09",
    code: "BZ-36",
    model: "Gemini",
    scope: "Brazil",
    category: "Finance & Economy",
    content: "The '4-Day Work Week' becomes a standard retention asset for elite tech and creative talent.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Brain drain crisis in São Paulo and Florianópolis forces flexibility to be valued above salary increases."
  },
  {
    id: "bz-gemini-10",
    code: "BZ-37",
    model: "Gemini",
    scope: "Brazil",
    category: "Politics",
    content: "The Amazon Fund reaches historic execution levels with capital flow into bioeconomy startups.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Post-COP30 pressure shifts regional economy from extraction to value-added processing."
  },
  {
    id: "bz-gemini-11",
    code: "BZ-38",
    model: "Gemini",
    scope: "Brazil",
    category: "Tech",
    content: "Fragmentation of 'Globo' dominance as Creator Economy networks secure major national event rights.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Monopoly of attention officially fractures among the under-35 demographic."
  },
  {
    id: "bz-gemini-12",
    code: "BZ-39",
    model: "Gemini",
    scope: "Brazil",
    category: "Tech",
    content: "VTOL (Flying Taxi) regulation framework finalized with mapped air lanes over São Paulo.",
    confidence: 65,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "ANAC finalizes frameworks signaling the start of vertiport construction in high-end districts."
  },

  // GLOBAL (GL-27 to GL-38)
  {
    id: "gl-gemini-01",
    code: "GL-27",
    model: "Gemini",
    scope: "Global",
    category: "AI",
    content: "Rise of 'Agent-to-Agent' (A2A) Commerce where autonomous agents handle B2B procurement.",
    confidence: 92,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Sales shift from human-centric to algorithm-optimizing data interfaces."
  },
  {
    id: "gl-gemini-02",
    code: "GL-28",
    model: "Gemini",
    scope: "Global",
    category: "Tech",
    content: "The 'Splinternet' hardens into three distinct non-interoperable Western, Chinese, and Sovereign blocs.",
    confidence: 88,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Digital visas and data tariffs complicate operations for global SaaS companies."
  },
  {
    id: "gl-gemini-03",
    code: "GL-29",
    model: "Gemini",
    scope: "Global",
    category: "Finance & Economy",
    content: "Big Tech becomes Big Nuclear with giants acquiring fleets of Small Modular Reactors (SMRs).",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Inability of existing grids to support AI compute demand forces tech companies into utility roles."
  },
  {
    id: "gl-gemini-04",
    code: "GL-30",
    model: "Gemini",
    scope: "Global",
    category: "Finance & Economy",
    content: "Labor markets invert with a 'Human Premium' on high-value manual trades and empathy roles.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Cognitive tasks commoditized by AI; 'Made by Humans' becomes a luxury service certification."
  },
  {
    id: "gl-gemini-05",
    code: "GL-31",
    model: "Gemini",
    scope: "Global",
    category: "Tech",
    content: "CRISPR enters the Consumer Wellness space for longevity and epigenetic reprogramming.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Gene-editing expands to enhancement targeting UHNW individuals in deregulated jurisdictions."
  },
  {
    id: "gl-gemini-06",
    code: "GL-32",
    model: "Gemini",
    scope: "Global",
    category: "Crypto",
    content: "A G7 Nation (likely Japan or UK) adds Bitcoin to its Strategic Reserves to hedge volatility.",
    confidence: 65,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Legitimatization of 'digital gold' at the state level triggers massive institutional repricing."
  },
  {
    id: "gl-gemini-07",
    code: "GL-33",
    model: "Gemini",
    scope: "Global",
    category: "Tech",
    content: "The first 'Orbital Manufacturing' IPO occurs for microgravity-produced fiber optics and drugs.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Starship operationalization lowers launch costs enough to close the commercial loop."
  },
  {
    id: "gl-gemini-08",
    code: "GL-34",
    model: "Gemini",
    scope: "Global",
    category: "Politics",
    content: "The 'Right to Disconnect' becomes a globally recognized human right and EU 'Cognitive Liberty' bill.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Reaction to brain-computer interfaces and immersive AR glasses causing mental privacy concerns."
  },
  {
    id: "gl-gemini-09",
    code: "GL-35",
    model: "Gemini",
    scope: "Global",
    category: "War",
    content: "AI-driven drone 'Swarm Warfare' makes traditional heavy legacy tanks structurally obsolete.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Budgets pivot from carriers/tanks to hive-mind autonomous swarm logistics and jamming."
  },
  {
    id: "gl-gemini-10",
    code: "GL-36",
    model: "Gemini",
    scope: "Global",
    category: "Finance & Economy",
    content: "Water Futures become the most volatile asset class amid severe droughts and 'Cloud Seeding' disputes.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Fresh water becomes primary geopolitical friction point; emergence of specialized Water Hedge Funds."
  },
  {
    id: "gl-gemini-11",
    code: "GL-37",
    model: "Gemini",
    scope: "Global",
    category: "Tech",
    content: "Consumer revolt against 'Subscription-Only' car models forces massive regulatory right-to-repair action.",
    confidence: 95,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Backlash against hardware feature paywalls leads to jailbreak communities and ownership protection laws."
  },
  {
    id: "gl-gemini-12",
    code: "GL-38",
    model: "Gemini",
    scope: "Global",
    category: "Tech",
    content: "Collapse of 4-Year University Degrees for tech roles, replaced by verified blockchain micro-credentials.",
    confidence: 88,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Employers drop degree requirements for 80% of roles in favor of simulation-verified 'Skill Wallets'."
  },

  // GEOPOLITICS (GP-25 to GP-36)
  {
    id: "gp-gemini-01",
    code: "GP-25",
    model: "Gemini",
    scope: "Geopolitics",
    category: "War",
    content: "The 'Korean Solution' settles over Ukraine with a de facto DMZ border.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Active frontline calcifies; EU peacekeepers deploy to the Western side to guarantee security."
  },
  {
    id: "gp-gemini-02",
    code: "GP-26",
    model: "Gemini",
    scope: "Geopolitics",
    category: "Politics",
    content: "A 'Gray Zone Quarantine' of Taiwan by China chokes economy via 'security compliance' inspections.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Falls short of war but forces administrative control over trade, paralyzing allies."
  },
  {
    id: "gp-gemini-03",
    code: "GP-27",
    model: "Gemini",
    scope: "Geopolitics",
    category: "Politics",
    content: "The 'Polar Silk Road' becomes the primary year-round artery for Russia-China trade.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Arctic Council collapse as joint naval patrols bypass traditional US-controlled bottlenecks."
  },
  {
    id: "gp-gemini-04",
    code: "GP-28",
    model: "Gemini",
    scope: "Geopolitics",
    category: "War",
    content: "The 'Red Sea Toll' becomes permanent as high-tech drone swarms make the route uninsurable.",
    confidence: 88,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Forced reconfiguration around Africa structurally increases global inflation long-term."
  },
  {
    id: "gp-gemini-05",
    code: "GP-29",
    model: "Gemini",
    scope: "Geopolitics",
    category: "Politics",
    content: "Lithium OPEC (LIPEC) formalized by South American producers to coordinate pricing.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Cartelization in response to Western and Chinese pressure to secure cheap EV supply chains."
  },
  {
    id: "gp-gemini-06",
    code: "GP-30",
    model: "Gemini",
    scope: "Geopolitics",
    category: "Politics",
    content: "The 'Sahel Belt' completely exits the Western sphere, signing 'Resource-for-Security' pacts with East.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Expulsion of final Western outposts creates contiguous hostile bloc cutting Africa in half."
  },
  {
    id: "gp-gemini-07",
    code: "GP-31",
    model: "Gemini",
    scope: "Geopolitics",
    category: "Politics",
    content: "G20 effectively replaces the UN Security Council for global crisis management.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "UNSC paralysis leads to binding security resolutions passed by coalitions of the willing within G20."
  },
  {
    id: "gp-gemini-08",
    code: "GP-32",
    model: "Gemini",
    scope: "Geopolitics",
    category: "War",
    content: "US adopts 'Fortress America' Naval Doctrine, deprioritizing protection of non-North American lanes.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "End of WWII deal where US Navy subsidized global trade security; allies forced to self-escort."
  },
  {
    id: "gp-gemini-09",
    code: "GP-33",
    model: "Gemini",
    scope: "Geopolitics",
    category: "Politics",
    content: "India asserts 'The Third Pole' doctrine, leading a 'Non-Aligned Tech Alliance'.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Leveraging digital stack capacity to offer alternatives to US and Chinese digital models."
  },
  {
    id: "gp-gemini-10",
    code: "GP-34",
    model: "Gemini",
    scope: "Geopolitics",
    category: "War",
    content: "First 'Orbital Denial' soft-weaponization event forces commercial constellation maneuvering.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Low Earth Orbit (LEO) proves to be a contested warfighting domain, no longer a sanctuary."
  },
  {
    id: "gp-gemini-11",
    code: "GP-35",
    model: "Gemini",
    scope: "Geopolitics",
    category: "Politics",
    content: "Fragmentation of Schengen as key EU nations reintroduce permanent physical border checks.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Pressure from migration waves and conflict drives death of borderless travel dream."
  },
  {
    id: "gp-gemini-12",
    code: "GP-36",
    model: "Gemini",
    scope: "Geopolitics",
    category: "Politics",
    content: "The 'Seabed Mining' rush begins as moratoriums are ignored for cobalt and nickel demand.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Pacific nations backed by high-tech mining firms ignore slow regulatory processes."
  },

  // ==========================================
  // BATCH 4: Perplexity (January 03, 2026)
  // ==========================================

  // BRAZIL (BZ-40 to BZ-57)
  {
    id: "bz-perp-01",
    code: "BZ-40",
    model: "Perplexity",
    scope: "Brazil",
    category: "Politics",
    content: "Lula will face a significant governability crisis in the second half of 2026 due to Congressional fragmentation.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Fragile legislative alliances and rising fiscal tensions will paralyze structural reforms."
  },
  {
    id: "bz-perp-02",
    code: "BZ-41",
    model: "Perplexity",
    scope: "Brazil",
    category: "Politics",
    content: "2026 Municipal elections will serve as a definitive thermometer of government rejection in major capitals.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Right-wing consolidation in medium cities and loss of PT hegemony in the South and Southeast."
  },
  {
    id: "bz-perp-03",
    code: "BZ-42",
    model: "Perplexity",
    scope: "Brazil",
    category: "Politics",
    content: "A 'Lava Jato 2.0' wave of investigations will target federal and state level corruption once again.",
    confidence: 65,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "New whistleblower testimonies regarding institutionalized misuse of federal funds will trend in Q3."
  },
  {
    id: "bz-perp-04",
    code: "BZ-43",
    model: "Perplexity",
    scope: "Brazil",
    category: "Finance & Economy",
    content: "Inflation will return to the 5-6% range by late 2026, driven by currency pressure and energy costs.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Dollar remaining above R$ 5.50 and persistent global supply chain friction affecting domestic prices."
  },
  {
    id: "bz-perp-05",
    code: "BZ-44",
    model: "Perplexity",
    scope: "Brazil",
    category: "Finance & Economy",
    content: "Unemployment will remain stuck above 8% as informal labor continues to dominate the market.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Despite formal job creation, real wage compression forces many into the gig economy."
  },
  {
    id: "bz-perp-06",
    code: "BZ-45",
    model: "Perplexity",
    scope: "Brazil",
    category: "Finance & Economy",
    content: "Brazilian Agribusiness will face implacable pressure for traceability and environmental compliance.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "International trade embargos and strict EU regulations will impact meat and soy export volumes."
  },
  {
    id: "bz-perp-07",
    code: "BZ-46",
    model: "Perplexity",
    scope: "Brazil",
    category: "Tech",
    content: "A brutal consolidation of the startup sector will occur, with only 20-30% of players surviving.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Tech giants like Nubank and Ambev will acquire cheap technology as VC funding dries up."
  },
  {
    id: "bz-perp-08",
    code: "BZ-47",
    model: "Perplexity",
    scope: "Brazil",
    category: "AI",
    content: "Generative AI will enter a 'disenchantment phase' in the Brazilian corporate sector.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Companies will realize that hype doesn't equal utility, leading to a 30% drop in speculative AI investment."
  },
  {
    id: "bz-perp-09",
    code: "BZ-48",
    model: "Perplexity",
    scope: "Brazil",
    category: "Tech",
    content: "Cybersecurity will become a critical national priority following high-profile breaches.",
    confidence: 95,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Ransomware attacks on government entities will prompt a massive hardening of LGPD enforcement."
  },
  {
    id: "bz-perp-10",
    code: "BZ-49",
    model: "Perplexity",
    scope: "Brazil",
    category: "Tech",
    content: "5G will reach 60% of cities but the rural digital divide will significantly deepen.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Infrastructure deployment will focus on high-density urban zones, leaving 40% of rural areas disconnected."
  },
  {
    id: "bz-perp-11",
    code: "BZ-50",
    model: "Perplexity",
    scope: "Brazil",
    category: "Crypto",
    content: "Bitcoin will experience extreme volatility between $35k and $65k in 2026.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Brazilian regulatory tightening on gains and KYC will flush out smaller speculative platforms."
  },
  {
    id: "bz-perp-12",
    code: "BZ-51",
    model: "Perplexity",
    scope: "Brazil",
    category: "Crypto",
    content: "Stablecoins (USDC/USDT) will become a de facto parallel currency for P2P transactions.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Informal dollarization will accelerate as individuals hedge against BRL instability."
  },
  {
    id: "bz-perp-13",
    code: "BZ-52",
    model: "Perplexity",
    scope: "Brazil",
    category: "War",
    content: "Urban violence in major Brazilian cities will reach a new plateau controlled by criminal factions.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Factions will expand territorial control despite intensified (but ineffective) police operations."
  },
  {
    id: "bz-perp-14",
    code: "BZ-53",
    model: "Perplexity",
    scope: "Brazil",
    category: "Tech",
    content: "Digital security will be perceived as more important than physical security by most Brazilians.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "60% growth in online fraud and WhatsApp scams will target the elderly and mid-income brackets."
  },
  {
    id: "bz-perp-15",
    code: "BZ-54",
    model: "Perplexity",
    scope: "Brazil",
    category: "Sports",
    content: "The 2026 World Cup will be a national disaster, with Brazil exiting in the Quarterfinals.",
    confidence: 60,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "The coaching staff will be fired following a major identity crisis in Brazilian football philosophy."
  },
  {
    id: "bz-perp-16",
    code: "BZ-55",
    model: "Perplexity",
    scope: "Brazil",
    category: "Sports",
    content: "Brazil will face a massive talent exodus as young stars flee legacy clubs for Europe and MLS.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Decreasing TV revenue and lack of domestic competitiveness will accelerate the brain drain."
  },
  {
    id: "bz-perp-17",
    code: "BZ-56",
    model: "Perplexity",
    scope: "Brazil",
    category: "Sports",
    content: "A mental health collapse will occur among Brazilian youth, with anxiety rates rising 25%.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Over-saturation of social media and lack of adequate public support systems will trigger a crisis."
  },
  {
    id: "bz-perp-18",
    code: "BZ-57",
    model: "Perplexity",
    scope: "Brazil",
    category: "Politics",
    content: "Political polarization will reach its maximum peak, with non-existent dialogue between blocs.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Instability risk will be real as institutional pressure mounts during the election cycle."
  },

  // GLOBAL (GL-39 to GL-50)
  {
    id: "gl-perp-01",
    code: "GL-39",
    model: "Perplexity",
    scope: "Global",
    category: "Politics",
    content: "The US-China Cold War will escalate into a near-total economic decoupling.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "40%+ tariffs on Chinese goods will fracture tech supply chains permanently."
  },
  {
    id: "gl-perp-02",
    code: "GL-40",
    model: "Perplexity",
    scope: "Global",
    category: "War",
    content: "The Ukraine war will settle into a 'frozen conflict' phase with permanent stalemates.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "NATO expansion will continue, but territorial advances for either side will cease."
  },
  {
    id: "gl-perp-03",
    code: "GL-41",
    model: "Perplexity",
    scope: "Global",
    category: "War",
    content: "The Middle East will remain a powder keg with US influence collapsing by 40%.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Iran nuclear acceleration and Saudi Arabia's pivot to China will destabilize the region."
  },
  {
    id: "gl-perp-04",
    code: "GL-42",
    model: "Perplexity",
    scope: "Global",
    category: "Finance & Economy",
    content: "A global recession will hit in Q2-Q3 2026, forcing major rate cuts by Q4.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "AI speculative bubble will burst hardest, leading to a 25-35% market correction."
  },
  {
    id: "gl-perp-05",
    code: "GL-43",
    model: "Perplexity",
    scope: "Global",
    category: "Crypto",
    content: "Crypto markets will implode to yearly lows before rebounding in late 2026.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "70% of altcoins will disappear as regulation and recession flush out weak players."
  },
  {
    id: "gl-perp-06",
    code: "GL-44",
    model: "Perplexity",
    scope: "Global",
    category: "Finance & Economy",
    content: "Real estate markets in developed nations will face a 15-25% price correction.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Office vacancy reaching 30% will make commercial real estate toxic for lenders."
  },
  {
    id: "gl-perp-07",
    code: "GL-45",
    model: "Perplexity",
    scope: "Global",
    category: "AI",
    content: "An 'AI Winter' will arrive as hype dies down and enterprise ROI is demanded.",
    confidence: 65,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Meta's Llama models will dominate open-source as closed-model valuations collapse."
  },
  {
    id: "gl-perp-08",
    code: "GL-46",
    model: "Perplexity",
    scope: "Global",
    category: "Tech",
    content: "Cybersecurity will become an existential threat following a major US power grid breach.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Nation-states will weaponize AI for hacking, exceeding $100B in global damages."
  },
  {
    id: "gl-perp-09",
    code: "GL-47",
    model: "Perplexity",
    scope: "Global",
    category: "Tech",
    content: "A major practical milestone in Quantum Computing will be achieved by Google or IBM.",
    confidence: 55,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Real-world problem solving in quantum advantage will make current encryption standards obsolete."
  },
  {
    id: "gl-perp-10",
    code: "GL-48",
    model: "Perplexity",
    scope: "Global",
    category: "Finance & Economy",
    content: "Oil prices will spike to $110 before a massive surge in renewable investment.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Geopolitical tensions in H1 will trigger structural shifts toward energy independence."
  },
  {
    id: "gl-perp-11",
    code: "GL-49",
    model: "Perplexity",
    scope: "Global",
    category: "Politics",
    content: "Climate disasters will cause $500B+ in global damages and reshape insurance industries.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Food price spikes of 20-30% will trigger significant climate-driven migration crises."
  },
  {
    id: "gl-perp-12",
    code: "GL-50",
    model: "Perplexity",
    scope: "Global",
    category: "Tech",
    content: "Social Media dominance will fracture, with decentralized networks reaching 100M+ users.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "TikTok bans and trust hitting all-time lows will force users into fragmented echo chambers."
  },

  // GEOPOLITICS (GP-37 to GP-48)
  {
    id: "gp-perp-01",
    code: "GP-37",
    model: "Perplexity",
    scope: "Geopolitics",
    category: "Politics",
    content: "US Hegemony enters a terminal decline phase as a multipolar world order stabilizes.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Dollar status will face the first serious challenge from digital BRICS alternatives."
  },
  {
    id: "gp-perp-02",
    code: "GP-38",
    model: "Perplexity",
    scope: "Geopolitics",
    category: "Politics",
    content: "Mexico will become the primary Geopolitical pivot point between US and China spheres.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "USMCA renegotiation will face pressure as Mexico deepens secret Chinese tech ties."
  },
  {
    id: "gp-perp-03",
    code: "GP-39",
    model: "Perplexity",
    scope: "Geopolitics",
    category: "Politics",
    content: "Latin America will pivot decisively toward China as its largest trading partner.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Argentina, Chile, and Peru will expand Belt and Road initiatives despite US protest."
  },
  {
    id: "gp-perp-04",
    code: "GP-40",
    model: "Perplexity",
    scope: "Geopolitics",
    category: "Politics",
    content: "The EU will fracture over internal disagreements on Ukraine and energy policy.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Germany energy costs and France pushing for military independence will paralyze the union."
  },
  {
    id: "gp-perp-05",
    code: "GP-41",
    model: "Perplexity",
    scope: "Geopolitics",
    category: "War",
    content: "NATO will expand to 34+ members but lose overall strategic cohesion.",
    confidence: 65,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Internal contradictions and aid fatigue will question the alliance's long-term credibility."
  },
  {
    id: "gp-perp-06",
    code: "GP-42",
    model: "Perplexity",
    scope: "Geopolitics",
    category: "Politics",
    content: "Russia will consolidate its Eurasian sphere of influence within the Chinese orbit.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Sanctions will force a permanent self-sufficient (but poorer) alignment with Beijing."
  },
  {
    id: "gp-perp-07",
    code: "GP-43",
    model: "Perplexity",
    scope: "Geopolitics",
    category: "War",
    content: "The Israel-Palestine conflict will reignite, triggering Hezbollah involvement in late 2026.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Ceasefire collapse and US military stretching will trigger a major regional escalation."
  },
  {
    id: "gp-perp-08",
    code: "GP-44",
    model: "Perplexity",
    scope: "Geopolitics",
    category: "Politics",
    content: "Iran will become a de facto nuclear threshold state while the West remains paralyzed.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Enrichment to 90% purity will shift the regional balance of power in Iran's favor."
  },
  {
    id: "gp-perp-09",
    code: "GP-45",
    model: "Perplexity",
    scope: "Geopolitics",
    category: "Politics",
    content: "The Saudi-China strategic alliance will deepen, marking the end of US Middle East dominance.",
    confidence: 88,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Petrodollar system will face an existential threat as oil is settled in digital yuan."
  },
  {
    id: "gp-perp-10",
    code: "GP-46",
    model: "Perplexity",
    scope: "Geopolitics",
    category: "War",
    content: "The Taiwan Strait will become a permanent flashpoint testing US military resolve.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "China's 'Customs Quarantine' doctrine will force a dangerous game of maritime brinkmanship."
  },
  {
    id: "gp-perp-11",
    code: "GP-47",
    model: "Perplexity",
    scope: "Geopolitics",
    category: "Politics",
    content: "India will emerge as the undisputed US counterweight to China in the Indo-Pacific.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "A Non-Aligned Tech Alliance led by India will challenge Chinese digital authoritarianism."
  },
  {
    id: "gp-perp-12",
    code: "GP-48",
    model: "Perplexity",
    scope: "Geopolitics",
    category: "Politics",
    content: "ASEAN will fracture into US-aligned and China-aligned camps by end of 2026.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "South China Sea claims will break regional unity as economic competition intensifies."
  },

  // ==========================================
  // BATCH 5: Claude 4.5 Haiku (January 03, 2026)
  // ==========================================

  // BRAZIL (BZ-58 to BZ-69)
  {
    id: "bz-claude-01",
    code: "BZ-58",
    model: "Claude",
    scope: "Brazil",
    category: "Politics",
    content: "Legislative 'Super-Bloc' forms in the National Congress to act as a definitive check on Executive powers.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Rising institutional friction leads to a strategic regrouping of center parties to control the budget agenda."
  },
  {
    id: "bz-claude-02",
    code: "BZ-59",
    model: "Claude",
    scope: "Brazil",
    category: "Finance & Economy",
    content: "Brazil's Debt-to-GDP ratio stabilizes better than IMF forecasts due to a tax reform windfall.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "The 2024-2025 tax transition yields higher-than-expected efficiency in collection from the digital services sector."
  },
  {
    id: "bz-claude-03",
    code: "BZ-60",
    model: "Claude",
    scope: "Brazil",
    category: "Tech",
    content: "Pix introduces mandatory 'Biometric Identity' verification layers for all transactions over R$ 1,000.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Response to the massive 2025 synthetic voice/video fraud surge that targeted the banking system."
  },
  {
    id: "bz-claude-04",
    code: "BZ-61",
    model: "Claude",
    scope: "Brazil",
    category: "Politics",
    content: "Rio de Janeiro establishes the first state-funded 'Digital Nomad Hub' zone with specialized tax incentives.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Strategic move to revitalize downtown areas and attract international tech talent to the service economy."
  },
  {
    id: "bz-claude-05",
    code: "BZ-62",
    model: "Claude",
    scope: "Brazil",
    category: "Sports",
    content: "Brazil's youth swimming team breaks a 20-year global drought, securing multiple gold medals in major world meets.",
    confidence: 65,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "New private investment cycles in high-performance centers begin showing results for the 'Generation 2028'."
  },
  {
    id: "bz-claude-06",
    code: "BZ-63",
    model: "Claude",
    scope: "Brazil",
    category: "Crypto",
    content: "DREX smart contracts for real estate rent and utilities become the standard in at least 5 Brazilian states.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Central Bank successfully bridges the gap between DREX infrastructure and retail utility apps."
  },
  {
    id: "bz-claude-07",
    code: "BZ-64",
    model: "Claude",
    scope: "Brazil",
    category: "Politics",
    content: "The 'Bio-Economy Tax Credit' bill passes, specifically targeting Amazon-based cosmetic and pharmaceutical firms.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Post-COP30 political consensus shifts toward value-added production within the forest regions."
  },
  {
    id: "bz-claude-08",
    code: "BZ-65",
    model: "Claude",
    scope: "Brazil",
    category: "Finance & Economy",
    content: "A merger of two legacy retail chains creates a national champion capable of competing directly with Amazon Brazil.",
    confidence: 60,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Consolidation pressure from high interest rates and international competition forces a 'survival merger'."
  },
  {
    id: "bz-claude-09",
    code: "BZ-66",
    model: "Claude",
    scope: "Brazil",
    category: "Tech",
    content: "The STJ issues the first landmark conviction for a crime committed exclusively via 'Synthetic Voice' impersonation.",
    confidence: 95,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Judiciary moves rapidly to establish jurisprudence as AI-enhanced extortion becomes a top-tier security threat."
  },
  {
    id: "bz-claude-10",
    code: "BZ-67",
    model: "Claude",
    scope: "Brazil",
    category: "Tech",
    content: "Brazil's first 100% domestic silicon chip design for IoT agricultural sensors enters mass production.",
    confidence: 50,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Long-term investment in Ceitec 2.0 and agritech partnerships yields the first viable commercial 'agro-chip'."
  },
  {
    id: "bz-claude-11",
    code: "BZ-68",
    model: "Claude",
    scope: "Brazil",
    category: "Politics",
    content: "A newly formed environmental-tech party gains double-digit percentage support in early senate polling.",
    confidence: 45,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Disillusionment with traditional polarized blocs leads to a surge for a 'Green-Science' pragmatism movement."
  },
  {
    id: "bz-claude-12",
    code: "BZ-69",
    model: "Claude",
    scope: "Brazil",
    category: "Finance & Economy",
    content: "New labor laws establish the 'Digital Right to Disconnect', strictly regulating off-hours corporate communication.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "A response to the burnout epidemic in the Brazilian service sector following the 2024-2025 hybrid work boom."
  },

  // GLOBAL (GL-51 to GL-62)
  {
    id: "gl-claude-01",
    code: "GL-51",
    model: "Claude",
    scope: "Global",
    category: "AI",
    content: "AI 'Personalization' dominance leads to the emergence of millions of specialized niche-LLMs.",
    confidence: 92,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "General-purpose models hit data plateaus; the market shifts to hyper-optimized experts for specific industries."
  },
  {
    id: "gl-claude-02",
    code: "GL-52",
    model: "Claude",
    scope: "Global",
    category: "Finance & Economy",
    content: "The EU economy enters a period of 'Competitive Stagnation' vs the USA and major Asian powers.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Energy costs and regulatory overhead hamper growth while US tech dominance captures more global trade."
  },
  {
    id: "gl-claude-03",
    code: "GL-53",
    model: "Claude",
    scope: "Global",
    category: "Tech",
    content: "Carbon-capture technology receives global funding equivalent to the 1960s Apollo space race.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Climate urgency forces sovereign wealth funds into moonshot industrial atmospheric filtration projects."
  },
  {
    id: "gl-claude-04",
    code: "GL-54",
    model: "Claude",
    scope: "Global",
    category: "AI",
    content: "GLP-1 drugs for treating clinical addictions (alcohol/nicotine) enter massive global adoption.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Pivotal trials confirm the neural reward-pathway suppression effects extend far beyond metabolic health."
  },
  {
    id: "gl-claude-05",
    code: "GL-55",
    model: "Claude",
    scope: "Global",
    category: "Tech",
    content: "Hardware-based 'Truth Authenticity' chips become mandatory for professional-grade imaging equipment.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Global trust crisis in media forces a hardware-level 'C2PA' standard for digital evidence and news."
  },
  {
    id: "gl-claude-06",
    code: "GL-56",
    model: "Claude",
    scope: "Global",
    category: "Finance & Economy",
    content: "The first commercial Small Modular Reactor (SMR) starts feeding a sovereign grid in the UAE.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Nearing the completion of long-term nuclear diversification goals with next-gen factory-built reactor technology."
  },
  {
    id: "gl-claude-07",
    code: "GL-57",
    model: "Claude",
    scope: "Global",
    category: "Tech",
    content: "China successfully launches its second permanent space station module for international partners.",
    confidence: 88,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Consolidation of the 'Tiangong' expansion as the primary alternative for Global South orbital research."
  },
  {
    id: "gl-claude-08",
    code: "GL-58",
    model: "Claude",
    scope: "Global",
    category: "Politics",
    content: "G20 countries pass 'Algorithmic Management' laws to protect transparency for gig workers.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Global labor unions push back against automated firing and opaque wage-setting in the platform economy."
  },
  {
    id: "gl-claude-09",
    code: "GL-59",
    model: "Claude",
    scope: "Global",
    category: "Finance & Economy",
    content: "Global semiconductor supply finally reaches a surplus, drastically lowering consumer tech costs.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "2022-2024 fab construction cycles peak in capacity while consumer demand for legacy hardware cools."
  },
  {
    id: "gl-claude-10",
    code: "GL-60",
    model: "Claude",
    scope: "Global",
    category: "AI",
    content: "A breakthrough in 'Bio-printing' functional skin for major burn victims reaches clinical hospital scale.",
    confidence: 65,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Combination of generative biological design and high-precision micro-nozzle tech clears the FDA."
  },
  {
    id: "gl-claude-11",
    code: "GL-61",
    model: "Claude",
    scope: "Global",
    category: "Politics",
    content: "North Atlantic 'Heat Anomaly' triggers the first emergency multi-national naval cloud-seeding trial.",
    confidence: 60,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Ocean temperature records force a desperate attempt at 'Marine Cloud Brightening' to avoid coral collapse."
  },
  {
    id: "gl-claude-12",
    code: "GL-62",
    model: "Claude",
    scope: "Global",
    category: "AI",
    content: "'Anti-Loneliness' AI companions become the most downloaded non-gaming app category globally.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Reasoning models finally cross the 'Emotional IQ' threshold needed for sustained human companionship."
  },

  // GEOPOLITICS (GP-49 to GP-60)
  {
    id: "gp-claude-01",
    code: "GP-49",
    model: "Claude",
    scope: "Geopolitics",
    category: "Politics",
    content: "BRICS+ introduces a 'Trade-only' digital settlement token to officially bypass the SWIFT system.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Need for sanction-proof financial corridors drives the technical unification of digital sovereign currencies."
  },
  {
    id: "gp-claude-02",
    code: "GP-50",
    model: "Claude",
    scope: "Geopolitics",
    category: "Finance & Economy",
    content: "A massive Solar-Hydrogen corridor is announced connecting Saudi Arabia directly to the Levant/Europe.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Energy security shift as the EU seeks long-term gas alternatives from stable Middle Eastern tech hubs."
  },
  {
    id: "gp-claude-03",
    code: "GP-51",
    model: "Claude",
    scope: "Geopolitics",
    category: "Politics",
    content: "Japan and Australia sign a 'Deep Security' maritime pact, essentially merging naval intelligence.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Regional concerns over Pacific trade route security force a departure from legacy independent doctrines."
  },
  {
    id: "gp-claude-04",
    code: "GP-52",
    model: "Claude",
    scope: "Geopolitics",
    category: "Politics",
    content: "Nigeria becomes the West's primary strategic partner for secure green-mineral sourcing in Africa.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Major infrastructure trades for lithium/cobalt rights move the geopolitical center of gravity to Lagos."
  },
  {
    id: "gp-claude-05",
    code: "GP-53",
    model: "Claude",
    scope: "Geopolitics",
    category: "Politics",
    content: "Internal migration within the EU shifts toward Northern countries due to extreme Southern heatwaves.",
    confidence: 85,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Demographic and labor reality shifts as climate habitability impacts real estate and job markets."
  },
  {
    id: "gp-claude-06",
    code: "GP-54",
    model: "Claude",
    scope: "Geopolitics",
    category: "Politics",
    content: "Greenland enters formal 'Free Association' talks to independently leverage its rare-earth resources.",
    confidence: 65,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Melting ice reveals multi-trillion dollar deposits, triggering a sovereign push away from Danish control."
  },
  {
    id: "gp-claude-07",
    code: "GP-55",
    model: "Claude",
    scope: "Geopolitics",
    category: "Finance & Economy",
    content: "The US-Mexico 'Silicon Corridor' becomes the world's highest value land border trade zone.",
    confidence: 90,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Completion of major near-shoring chip assembly plants in Northern Mexico transforms regional trade."
  },
  {
    id: "gp-claude-08",
    code: "GP-56",
    model: "Claude",
    scope: "Geopolitics",
    category: "Politics",
    content: "The UN discusses the first 'Cyber-Neutrality' treaties to protect civilian digital infrastructure in conflicts.",
    confidence: 70,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Global realization that disabling a power grid or hospital via code is equivalent to a kinetic war crime."
  },
  {
    id: "gp-claude-09",
    code: "GP-57",
    model: "Claude",
    scope: "Geopolitics",
    category: "Politics",
    content: "The Philippines establishes a permanent, solar-powered research base on a contested Pacific shoal.",
    confidence: 80,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Strategic 'fait accompli' move to secure EEZ rights with non-military permanent civilian presence."
  },
  {
    id: "gp-claude-10",
    code: "GP-58",
    model: "Claude",
    scope: "Geopolitics",
    category: "Politics",
    content: "Major reconstruction of Gaza starts under a multi-national trust led by GCC nations.",
    confidence: 60,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Exhaustion of all parties leads to a technical 'Marshall Plan' focused on infrastructure and security."
  },
  {
    id: "gp-claude-11",
    code: "GP-59",
    model: "Claude",
    scope: "Geopolitics",
    category: "Politics",
    content: "The 'G2' (US-China) relations enter a 'Cold Peace' with explicit, monitored red lines.",
    confidence: 75,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "Both nations realize economic mutual destruction is too high, opting for strictly regulated competition."
  },
  {
    id: "gp-claude-12",
    code: "GP-60",
    model: "Claude",
    scope: "Geopolitics",
    category: "Tech",
    content: "India joins the US and China in the 'Nuclear-Space-Propulsion' race for faster Martian transit.",
    confidence: 50,
    status: "Pending",
    timestamp: "2026-01-03",
    reasoning: "The success of the Chandrayaan-4 mission triggers a multi-decade budget for deep-space energy tech."
  }
];
